version: '3'

services:
  app:
    build: node
    container_name: app
    entrypoint: wait-for db:3306 -t 40 -- ./start.sh
    tty: true
    networks:
      - node-network
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge